# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'appcentertest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for appcentertest
  pod 'AppCenter/Crashes', '~> 1.7.1'
  pod 'AppCenter/Analytics', '~> 1.7.1'
  pod 'AppCenterReactNativeShared', '~> 1.6.0'

  

  platform :ios, '9.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'appcentertestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'appcentertest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for appcentertest-tvOS

  target 'appcentertest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
